Added update latest version

diff --git a/build-for-release-pipeline.yml b/build-for-release-pipeline.yml
--- a/build-for-release-pipeline.yml
+++ b/build-for-release-pipeline.yml
@@ -1243,3 +1243,51 @@ extends:
                     tree
                     cat packages.csv
                   displayName: 'Debug'
+
+      - ${{ if eq(parameters.update_version, true) }}:
+        - stage: UpdateLatestVersion
+          dependsOn:
+            - AzCopyVersion
+            - VerifyArtifacts
+          jobs:
+            - job: Job
+              pool:
+                name: azcopy-pool
+                image: ubuntu22-1espt
+                os: linux
+              variables:
+                - name: azcopy_version
+                  value: $[ stageDependencies.AzCopyVersion.GetAzCopyVersion.outputs['SetAzCopyVersion.azcopy_version'] ]
+              steps:
+                - checkout: self
+                  displayName: 'Checkout repository'
+
+                - task: GoTool@0
+                  env:
+                    GO111MODULE: 'on'
+                  inputs:
+                    version: $(AZCOPY_GOLANG_VERSION)
+
+                - script: |
+                    go build -tags "netgo" -o azcopy
+                  displayName: 'Build AzCopy'
+
+                - task: AzureCLI@2
+                  inputs:
+                    azureSubscription: 'ESRP KeyVault identity'
+                    scriptType: bash
+                    scriptLocation: inlineScript
+                    inlineScript: |
+                      echo "azcopy version: $azcopy_version"
+                      #Upload to release version blob file
+                      upload_url="https://azcopyprivatedrops.blob.core.windows.net/%24web/releasemetadata/latest_version.txt"
+                      echo "$azcopy_version" | azcopy copy "$upload_url" --from-to=PipeBlob --log-level=DEBUG --output-type=text > azcopy_output.txt
+                      
+                      # Handle errors 
+                      if [ $? -eq 0 ]; then
+                        echo "Release version file successfully uploaded."
+                      else
+                        echo "File failed to upload: "
+                        cat azcopy_output.txt
+                        exit 1
+                      fi
