try to upload

diff --git a/build-for-release-pipeline.yml b/build-for-release-pipeline.yml
--- a/build-for-release-pipeline.yml
+++ b/build-for-release-pipeline.yml
@@ -35,66 +35,66 @@ extends:
         image: windows2022-1espt
         os: windows  # OS of the image. Allowed values: windows, linux, macOS
     stages:
-#      - stage: AzCopyVersion
-#        jobs:
-#          - job: GetAzCopyVersion
-#            pool:
-#              name: azcopy-pool
-#              image: ubuntu22-1espt
-#              os: linux
-#            # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
-#            # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
-#            templateContext:
-#              outputs:
-#                - output: pipelineArtifact
-#                  targetPath: $(System.DefaultWorkingDirectory)/releasehelper
-#                  artifactName: 'azcopy-releasehelper'
-#                  displayName: 'Upload Release Helper Files'
-#            variables:
-#              - name: output_path
-#                value: '$(System.DefaultWorkingDirectory)/releasehelper'
-#            steps:
-#              - checkout: self
-#                displayName: 'Checkout repository'
-#
-#              - task: GoTool@0
-#                env:
-#                  GO111MODULE: 'on'
-#                inputs:
-#                  version: $(AZCOPY_GOLANG_VERSION)
-#
-#              - script: |
-#                  go build -tags "netgo" -o azcopy
-#                displayName: 'Build AzCopy'
-#
-#              - script: |
-#                  # Run azcopy --version and capture the output
-#                  azcopyOutput=$(./azcopy --version)
-#
-#                  # Extract the version part
-#                  if echo "$azcopyOutput" | grep -q "azcopy version"; then
-#                    version=$(echo "$azcopyOutput" | sed -n 's/^azcopy version \([0-9]*\.[0-9]*\.[0-9]*[^ ]*\).*/\1/p')
-#                    if [[ -n "$version" ]]; then
-#                      echo "Extracted version: $version"
-#                      echo "##vso[task.setvariable variable=azcopy_version;isOutput=true]$version"
-#                    else
-#                      echo "Unable to extract version from azcopy output"
-#                      exit 1
-#                    fi
-#                  else
-#                    echo "azcopy version string not found in output"
-#                    exit 1
-#                  fi
-#                displayName: 'Verify and extract the generated build version'
-#                name: SetAzCopyVersion
-#
-#              - script: |
-#                  mkdir -p $(output_path)
-#                  cp docker/Dockerfile* $(output_path)
-#                  echo $(azcopy_version) > $(output_path)/latest_version.txt
-#                  cp NOTICE.txt $(output_path)
-#                  cp packages.csv $(output_path)
-#                displayName: 'Release Helper Files'
+      - stage: AzCopyVersion
+        jobs:
+          - job: GetAzCopyVersion
+            pool:
+              name: azcopy-pool
+              image: ubuntu22-1espt
+              os: linux
+            # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
+            # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
+            templateContext:
+              outputs:
+                - output: pipelineArtifact
+                  targetPath: $(System.DefaultWorkingDirectory)/releasehelper
+                  artifactName: 'azcopy-releasehelper'
+                  displayName: 'Upload Release Helper Files'
+            variables:
+              - name: output_path
+                value: '$(System.DefaultWorkingDirectory)/releasehelper'
+            steps:
+              - checkout: self
+                displayName: 'Checkout repository'
+
+              - task: GoTool@0
+                env:
+                  GO111MODULE: 'on'
+                inputs:
+                  version: $(AZCOPY_GOLANG_VERSION)
+
+              - script: |
+                  go build -tags "netgo" -o azcopy
+                displayName: 'Build AzCopy'
+
+              - script: |
+                  # Run azcopy --version and capture the output
+                  azcopyOutput=$(./azcopy --version)
+
+                  # Extract the version part
+                  if echo "$azcopyOutput" | grep -q "azcopy version"; then
+                    version=$(echo "$azcopyOutput" | sed -n 's/^azcopy version \([0-9]*\.[0-9]*\.[0-9]*[^ ]*\).*/\1/p')
+                    if [[ -n "$version" ]]; then
+                      echo "Extracted version: $version"
+                      echo "##vso[task.setvariable variable=azcopy_version;isOutput=true]$version"
+                    else
+                      echo "Unable to extract version from azcopy output"
+                      exit 1
+                    fi
+                  else
+                    echo "azcopy version string not found in output"
+                    exit 1
+                  fi
+                displayName: 'Verify and extract the generated build version'
+                name: SetAzCopyVersion
+
+              - script: |
+                  mkdir -p $(output_path)
+                  cp docker/Dockerfile* $(output_path)
+                  echo $(azcopy_version) > $(output_path)/latest_version.txt
+                  cp NOTICE.txt $(output_path)
+                  cp packages.csv $(output_path)
+                displayName: 'Release Helper Files'
 #
 #      - stage: BuildArtifacts
 #        dependsOn: AzCopyVersion
@@ -905,6 +905,8 @@ extends:
                 value: '$(System.DefaultWorkingDirectory)/release'
               - name: drop
                 value: '$(System.DefaultWorkingDirectory)/drop'
+              - name: azcopy_version
+                value: $[ stageDependencies.AzCopyVersion.GetAzCopyVersion.outputs['SetAzCopyVersion.azcopy_version'] ]
             steps:
               - checkout: self
                 displayName: 'Checkout repository'
@@ -922,7 +924,7 @@ extends:
                   version: $(AZCOPY_GOLANG_VERSION)
 
               - script: |
-                  go build -tags "netgo" -o azcopy.exe
+                  go build -tags "netgo" -o azcopy
                 displayName: 'Build AzCopy'
 
               - script: |
@@ -946,3 +948,6 @@ extends:
                   scriptLocation: inlineScript
                   inlineScript: |
                     today=$(date +"%Y%m%d")
+                    container_url="https://azcopyprivatedrops.blob.core.windows.net/%24web/releases/release-$(azcopy_version)-$today"
+                    echo "Artifacts will be uploaded to: $container_url"
+                    AZCOPY_AUTO_LOGIN_TYPE=AzCLI ./azcopy cp "$(release)/*" "$container_url" --recursive --put-md5=true
